config/routes.rb
Between800::Application.routes.draw do
  resources :ranks

  root :to => "products#index"

end

app/models/rank.rb
class Rank < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
  # GET /ranks
  # GET /ranks.xml
  def index
    @ranks = Rank.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @ranks }
    end
  end

  # GET /ranks/1
  # GET /ranks/1.xml
  def show
    @rank = Rank.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @rank }
    end
  end

  # GET /ranks/new
  # GET /ranks/new.xml
  def new
    @rank = Rank.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @rank }
    end
  end

  # GET /ranks/1/edit
  def edit
    @rank = Rank.find(params[:id])
  end

  # POST /ranks
  # POST /ranks.xml
  def create
    @rank = Rank.new(params[:rank])

    respond_to do |format|
      if @rank.save
        format.html { redirect_to(@rank, :notice => 'Rank was successfully created.') }
        format.xml  { render :xml => @rank, :status => :created, :location => @rank }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @rank.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ranks/1
  # PUT /ranks/1.xml
  def update
    @rank = Rank.find(params[:id])

    respond_to do |format|
      if @rank.update_attributes(params[:rank])
        format.html { redirect_to(@rank, :notice => 'Rank was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @rank.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ranks/1
  # DELETE /ranks/1.xml
  def destroy
    @rank = Rank.find(params[:id])
    @rank.destroy

    respond_to do |format|
      format.html { redirect_to(ranks_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Between800</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/ranks/_form.html.erb
<%= form_for(@rank) do |f| %>
  <% if @rank.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rank.errors.count, "error") %> prohibited this rank from being saved:</h2>

      <ul>
      <% @rank.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rank %><br />
    <%= f.text_field :rank %>
  </div>
  <div class="field">
    <%= f.label :score %><br />
    <%= f.text_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ranks/edit.html.erb
<h1>Editing rank</h1>

<%= render 'form' %>

<%= link_to 'Show', @rank %> |
<%= link_to 'Back', ranks_path %>

app/views/ranks/index.html.erb
<h1>Listing ranks</h1>

<table>
  <tr>
    <th>Rank</th>
    <th>Score</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ranks.each do |rank| %>
  <tr>
    <td><%= rank.rank %></td>
    <td><%= rank.score %></td>
    <td><%= link_to 'Show', rank %></td>
    <td><%= link_to 'Edit', edit_rank_path(rank) %></td>
    <td><%= link_to 'Destroy', rank, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rank', new_rank_path %>

app/views/ranks/new.html.erb
<h1>New rank</h1>

<%= render 'form' %>

<%= link_to 'Back', ranks_path %>

app/views/ranks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Rank:</b>
  <%= @rank.rank %>
</p>

<p>
  <b>Score:</b>
  <%= @rank.score %>
</p>


<%= link_to 'Edit', edit_rank_path(@rank) %> |
<%= link_to 'Back', ranks_path %>